version: '2'

services:
 nginx:
  depends_on:
   - "php"

  image: "nginx"

  volumes:
   - "$PWD/conf/nginx/conf.d:/etc/nginx/conf.d"
   - "$PWD/../www:/usr/share/nginx/html"
  ports:
   - "80:80"
   - "443:443"
  networks:
   - oa-network
  restart: always
  container_name: "my-nginx"
  command: /bin/bash -c "mkdir -p /var/www && ln -s /usr/share/nginx/html /var/www && nginx -g 'daemon off;'"
  
 
 php:
  image: "oa-php-fpm"
  build:  
   context: .
   dockerfile: "Dockerfile.php"
  networks:
   - oa-network
  restart: always
  container_name: "my-php-fpm"
  volumes:
   - "$PWD/../www:/var/www/html"

 mysql:
  image: mysql:5.7
  volumes:
   - "$PWD/db_data:/var/lib/mysql"
  environment:
   MYSQL_ROOT_PASSWORD: 123456
   MYSQL_DATABASE: oa
   MYSQL_USER: root
   MYSQL_PASSWORD: 123456
  networks:
   - oa-network
  container_name: "my-mysql"

 redis:
  image: "redis"
  networks:
   - oa-network
  restart: always
  volumes:
   - "$PWD/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf"
  container_name: "my-redis"

networks:
 oa-network:
  driver: bridge
